name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        run: ./gradlew build --no-daemon  -x test

      - name: Execute Gradle Coverage
        run: ./gradlew check

      - name: Execute Gradle Coverage
        if: runner.os == 'macOS'
        run: bash <(curl -s https://codecov.io/bash)
