name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd comate-gui
          pnpm install
          pnpm build

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        run: ./gradlew build --no-daemon  -x test

      - name: Execute Gradle Coverage
        run: ./gradlew check

      - name: Coveralls
        uses: coverallsapp/github-action@v2
